FROM transfusion/deployapp-base-container:ol9-java17-23.0.0-dev-app-info-2.8.3

WORKDIR /app/

COPY gradlew build.gradle.kts settings.gradle.kts ./
COPY gradle ./gradle
# COPY .gradle ./.gradle
RUN ls -lah
RUN ./gradlew dependencies

# FROM ghcr.io/graalvm/graalvm-ce:ol8-java11-22.3.1
# COPY --from=builder /root/.gradle /root/.gradle
# WORKDIR /app
# COPY . /app
