FROM ghcr.io/graalvm/graalvm-ce:ol8-java11-22.3.1 as builder
# RUN gu install ruby && /opt/graalvm-ce-java11-22.3.1/languages/ruby/lib/truffle/post_install_hook.sh && gem install app-info -- --with-ldflags="-fno-lto" --with-cflags="-fno-lto"

WORKDIR /app/

COPY gradlew build.gradle build.gradle.kts settings.gradle ./
COPY gradle ./gradle
# COPY .gradle ./.gradle
RUN ls -lah
RUN ./gradlew dependencies

FROM ghcr.io/graalvm/graalvm-ce:ol8-java11-22.3.1
COPY --from=builder /root/.gradle /root/.gradle
# WORKDIR /app
# COPY . /app
