spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 250MB
      max-request-size: 250MB
  rabbitmq:
    host: dapp-rabbitmq
    port: 5672
    username: guest
    password: guest
  redis:
    host: dapp-redis
    port: 6379
    password: "password"
    flush-mode: immediate
  session:
    store-type: redis
    timeout: 2d
  flyway:
    enabled: true
    locations: "classpath:db/migration/{vendor}"
  # primary datasource
  datasource:
    username: "postgres"
    password: "password"
    url: "jdbc:postgresql://dapp-db:5432/deployapp_storage_dev_1"

# comma-separated, see https://github.com/spring-projects/spring-framework/issues/16381
custom_cors:
  origins: http://localhost:3000,https://deploy.plan.ovh

custom_app:
  lock_registry_key_prefix: "dapp_storage_lock"

# https://springdoc.org/
# https://stackoverflow.com/questions/65820916/i-have-installed-openapi-3-using-springdoc-but-the-url-is-strange-can-i-change
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui

microservice-endpoints:
 main: http://dapp-backend:8080

# for async processing with jobrunr
org:
  jobrunr:
    job-scheduler:
      enabled: true
    database:
      type: redis-lettuce
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5
    dashboard:
      enabled: false

custom_jobrunr:
  keepalive-interval: PT30S

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
#          filter:
#            CommonsRequestLoggingFilter: DEBUG

server:
  forward-headers-strategy: framework # https://github.com/springdoc/springdoc-openapi/issues/171
  servlet:
    session:
      cookie:
        # https://stackoverflow.com/questions/33095345/how-to-change-spring-session-redis-cookie-name
        name: "DEPLOYAPP_SESSION"
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true


